

# **Task Time**

Task time is the time taken to complete a task. Task can be short like a single knot or some longer complex task.

## Studies
```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
library(meta)
library(esc)
library(tidyverse)
library(stargazer)
library(readxl)
library(knitr)
```
Load data
```{r}
df.time <- read_excel('data/surgical_metrics.xlsx', sheet='task_time')
```
Print studies
```{r echo = FALSE, results = 'asis'}
kable(df.time[,c("Author", "Year", "Study", "Journal")])
```

## Results
```{r}
m.time <- metagen(TE=g,
                 seTE=SDg,
                 studlab=Author,
                 data=df.time,
                 sm="SMD",
                 fixed=FALSE,
                 random=TRUE,
                 method.tau="REML",
                 hakn=TRUE,
                 title="Time to completion in Surgery")
```
```{r}
summary(m.time)
```
Plot forest
```{r, fig.width = 10, fig.height=7}
forest.meta(m.time,sortvar=g, prediction=TRUE, prin.tau2=TRUE, title="Time to completion in Surgery")
#dev.print(pdf, "figures/forest_time.pdf", width=10, height=10)


```
## Discussion

Time to completion is by far the most often reported metric. It is often reported even when it is not the main focus of the study.




