# Bimanual dexterity

Bimanual dexterity is a measure of how well the surgeon is able to use both hands at the same time. Note that there are many different ways for calculating "ability to use both hands simultaneously."
```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
library(meta)
library(esc)
library(tidyverse)
library(stargazer)
library(readxl)
```
Load data
```{r}
df.biman <- read_excel('data/surgical_metrics.xlsx', sheet='tool_bimanual')
```
```{r}
m.biman <- metagen(TE=g,
                 seTE=SDg,
                 studlab=Author,
                 data=df.biman,
                 sm="SMD",
                 fixed=FALSE,
                 random=TRUE,
                 method.tau="REML",
                 hakn=TRUE,
                 title="Bimanual dexterity in Surgery")
```
```{r}
summary(m.biman)
```
Plot forest
```{r, fig.width = 10, fig.height=5}
forest.meta(m.biman,sortvar=g, prediction=TRUE, prin.tau2=TRUE, title="Bimanual dexterity in Surgery")
dev.print(pdf, "figures/forest_biman.pdf", width=8, height=8)
```
