---
title: "R Notebook"
output: html_notebook
---


```{r, results='hide', message=FALSE}
library(meta)
library(esc)
library(tidyverse)
library(stargazer)
```
Load data
```{r}
df <- read.csv('data/time_data.csv')
```
Show data. Data has time to completion results for novices and experts from different studies. Original time (Mn and Me) given in seconds.
```{r}
head(df, 1)
```

```{r}
m.gen <- metagen(TE=g,
                 seTE=SDg,
                 studlab=Author,
                 data=df,
                 sm="SMD",
                 fixed=FALSE,
                 random=TRUE,
                 method.tau="REML",
                 hakn=TRUE,
                 title="Time to completion in Surgery")
```
```{r}
summary(m.gen)
```
Plot forest
```{r, fig.width = 10,fig.height=10}
forest.meta(m.gen,sortvar=g, prediction=TRUE, prin.tau2=TRUE, title="Time to completion in Surgery")
dev.print(pdf, "forest_time.pdf", width=8, height=8)
```
Plot drapery
```{r, fig.width = 10,fig.height=10}
drapery(m.gen, labels="studlab", type="pval", legend=FALSE)
```
Standardized means
```{r}
m.cont <- metacont(n.e=Nn,
                   mean.e=Mn,
                   sd.e=SDn,
                   n.c=Ne,
                   mean.c=Me,
                   sd.c=SDe,
                   studlab=Author,
                   data=df,
                   sm="SMD",
                   method.smd="Hedges",
                   fixed=FALSE,
                   random=TRUE,
                   method.tau="REML",
                   hakn=TRUE,
                   title="Time to completion in Microsurgery")
```
Summary
```{r}
summary(m.cont)
```
Plot forest
```{r, fig.width = 10,fig.height=10}
forest.meta(m.cont,sortvar=SMD, prediction=TRUE, prin.tau2=TRUE)
```



