
# Grasps

Grasps are the number of times the surgeon had to grasp something using surgical instruments

## Results
```{r, results='hide', message=FALSE, echo=FALSE, warning=FALSE}
library(meta)
library(esc)
library(tidyverse)
library(stargazer)
library(readxl)
```
Load data
```{r}
df.grasp <- read_excel('data/surgical_metrics.xlsx', sheet='tool_grasps')
```

Run meta-analysis
```{r}
m.grasp <- metagen(TE=g,
                 seTE=SDg,
                 studlab=Author,
                 data=df.grasp,
                 sm="SMD",
                 fixed=FALSE,
                 random=TRUE,
                 method.tau="REML",
                 hakn=TRUE,
                 title="Grasping in Surgery")
```
```{r}
summary(m.grasp)
```

Plot forest
```{r, fig.width = 10, fig.height=5}
forest.meta(m.grasp,sortvar=g, prediction=TRUE, prin.tau2=TRUE, title="Time to completion in Surgery")
dev.print(pdf, "figures/forest_grasp.pdf", width=8, height=8)
```

## Discussion
Not many papers that focused on grasps. I have included thus the grasp results also to the "Tool movements" analysis.